- link:
      ~/.bashrc:        bash/bashrc
      ~/.bash_aliases:  bash/aliases
      ~/.bash_logout:   bash/logout
      ~/.bash_profile:  bash/profile

- git:
      "~/.oh-my-bash":
          url: "https://github.com/ohmybash/oh-my-bash"
          description: "oh my bash - core"
