#!/usr/bin/env bash

set -e
set -u
set -o pipefail
set -x

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DOTBOT_DIR="meta/dotbot"
PLUGINS_DIR="plugins"

CONFIG="install.conf.yaml"


DOTBOT_BIN="bin/dotbot"


cd "${BASEDIR}"

printf "%s %s\\n" "Submodules: sync" "${DOTBOT_DIR}"
git submodule sync --quiet --recursive || printf "%s %s\\n" "Submodules: failed sync" "${DOTBOT_DIR}"

# printf "%s %s\\n" "Submodules: update" "${DOTBOT_DIR}"
# git submodule update --init --quiet  --recursive "${DOTBOT_DIR}" || printf "%s %s\\n" "Submodules: failed update" "${DOTBOT_DIR}"

printf "%s %s\\n" "Submodules: update" "${BASEDIR}"
git submodule update --quiet  --init "${BASEDIR}" || printf "%s %s\\n" "Submodules: failed update" "${BASEDIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"  \
  --plugin-dir plugins/dotbot-snap \
  --plugin-dir plugins/dotbot-template \
"${@}"