#!/usr/bin/env bash

set -e
# set -u
set -o pipefail

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PLUGINS_DIR="plugins"

PROFILE_NAME=${1:-?}

DOTBOT_BIN="bin/dotbot"

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

while IFS= read -r config; do
	CONFIGS+=" ${config}"
done <"${META_DIR}/${PROFILES_DIR}/${PROFILE_NAME}"

shift

for config in ${CONFIGS} "${@}"; do
	echo -e "\nConfigure ${config}"
	configContent="$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}")"
	"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
		--plugin-dir "${META_DIR}"/"${PLUGINS_DIR}"/dotbot-snap \
		--plugin-dir "${META_DIR}"/"${PLUGINS_DIR}"/dotbot-template \
		-d "${BASE_DIR}" \
		-c <(echo -e "${configContent}")
done

# "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"  \
#   --plugin-dir plugins/dotbot-snap \
#   --plugin-dir plugins/dotbot-template \
# "${@}"
